[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/", 
"@openzepplin/contracts/=lib/openzeppelin-contracts/contracts"]        
fs_permissions = [{access = "read", path = "./img"}]
